spring.application.name=shift-backend
server.port=${PORT:8090}

spring.devtools.restart.enabled=false
server.forward-headers-strategy=framework
server.servlet.session.cookie.same-site=strict

spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.chain.cache=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shift_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1221}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

app.vehicle-card-upload.dir=${user.home}/.shift-backend/vehicle-card-uploads


